{% set name = "mopactools" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmopac/mopactools/archive/v{{ version }}.tar.gz
  sha256: c9e0a79437265199293152fc9dd6f44a94ef2ae774e016325b383e08a345655d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - packaging
    - mopac >=23.2.5

test:
  imports:
    - mopactools
    - mopactools.api
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/openmopac/mopactools
  summary: Productivity tools for MOPAC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - godotalgorithm
